// <auto-generated />
namespace Real_estate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class realEstate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(realEstate));
        
        string IMigrationMetadata.Id
        {
            get { return "202010150546373_realEstate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
